chapter18/pizzeria/pizzeria/urls.py
"""Define URL patterns for pizzeria."""

from django.urls import path

from . import views

app_name = 'pizzeria'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topic.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza.
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

chapter18/pizzeria/pz_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzeria.urls')),
]

chapter18/pizzeria/pizzeria/models.py
from django.db import models

class Pizza(models.Model):
    """A Pizza the user is ordering"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name
    
class Topping(models.Model):
    """A Topping to be put on the pizza"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.name[:50]}"

chapter18/pizzeria/pizzeria/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzeria/index.html')

def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzeria/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzeria/pizza.html', context)

chapter18/pizzeria/pizzeria/templates/pizzeria/base.html
<p>
  <a href="{% url 'pizzeria:index' %}">Pizzeria</a>
  <a href="{% url 'pizzeria:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

chapter18/pizzeria/pizzeria/templates/pizzeria/index.html
{% extends 'pizzeria/base.html' %} {% block content %}
<p>
  Welcome to the pizzeria! This is our home page, to inspect individual pizzas,
  click on the links. Click 'Pizzeria' to return to this page.
</p>
{% endblock content %}

chapter18/pizzeria/pizzeria/templates/pizzeria/pizza.html
{% extends 'pizzeria/base.html' %} {% block content %}
<p>Pizza: {{ pizza.name }}</p>

<p>Toppings:</p>
<ul>
  {% for topping in toppings %}
  <li>
    <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ topping.name|linebreaks }}</p>
  </li>
  {% empty %}
  <li>There are no toppings for this pizza yet.</li>
  {% endfor %}
</ul>
{% endblock content %}

chapter18/pizzeria/pizzeria/templates/pizzeria/pizzas.html
{% extends 'pizzeria/base.html' %} {% block content %}
<p>Pizzas</p>
<ul>
  {% for pizza in pizzas %}
  <li>
    <a href="{% url 'pizzeria:pizza' pizza.id %}">{{ pizza.name }}</a>
  </li>
  {% empty %}
  <li>No pizzas have been added yet.</li>
  {% endfor %}
</ul>
{% endblock content %}