chapter19/blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

chapter19/blog/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('blogs/', views.blogs, name='blogs'),
    # Detail page for a single topic.
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    # Page for adding a new topic.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for adding a new entry.
    path('new_blog_post/<int:blog_id>/', views.new_blog_post, name='new_blog_post'),
    # Page for editing an entry.
    path('edit_blog_post/<int:blog_post_id>/', views.edit_blog_post, name='edit_blog_post'),
]

chapter19/blog/blogs/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    """One person's blog."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name
    
class BlogPost(models.Model):
    """Individual psot."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.title) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

chapter19/blog/blogs/forms.py
from django import forms

from .models import Blog, BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body']
        labels = {'title': '', 'body': ''}        
        widgets = {'title': forms.Textarea(attrs={'cols': 80}), 
                   'body': forms.Textarea(attrs={'cols': 80})}

chapter19/blog/blogs/views.py
from django.shortcuts import render, redirect

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm

def index(request):
    """The homepage for blogs"""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Show all topics."""
    blogs = Blog.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Show a single topic and all its entries."""
    blog = Blog.objects.get(id=blog_id)
    blog_posts = blog.blogpost_set.order_by('-date_added')
    context = {'blog': blog, 'blog_posts': blog_posts}
    return render(request, 'blogs/blog.html', context)

def new_blog(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

def new_blog_post(request, blog_id):
    """Add a new entry for a particular topic."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_blog_post = form.save(commit=False)
            new_blog_post.blog = blog
            new_blog_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_blog_post.html', context)

def edit_blog_post(request, blog_post_id):
    """Edit an existing entry."""
    blog_post = BlogPost.objects.get(id=blog_post_id)
    blog = blog_post.blog

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogPostForm(instance=blog_post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=blog_post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)
        
    context = {'blog_post': blog_post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog_post.html', context)

chapter19/blog/blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">Home</a> -
  <a href="{% url 'blogs:blogs' %}">Blogs</a>
</p>

{% block content %}{% endblock content %}

chapter19/blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %} {% block content %}

<p>Blog: {{ blog.name }}</p>

<p>Blog Posts:</p>
<p><a href="{% url 'blogs:new_blog_post' blog.id %}">Add new blog post</a></p>
<ul>
  {% for blog_post in blog_posts %}
  <li>
    <p>{{ blog_post.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ blog_post.title|linebreaks }}</p>
    <p>{{ blog_post.body|linebreaks }}</p>

    <p>
      <a href="{% url 'blogs:edit_blog_post' blog_post.id %}">Edit blog post</a>
    </p>
  </li>
  {% empty %}
  <li>There are no blog posts for this blog yet.</li>
  {% endfor %}
</ul>
{% endblock content %}

chapter19/blog/blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %} {% block content %}

<p>Blogs</p>
<ul>
  {% for blog in blogs %}
  <li>
    <a href="{% url 'blogs:blog' blog.id%}">{{ blog.name }}</a>
  </li>
  {% empty %}
  <li>No blogs have been added yet.</li>
  {% endfor %}
</ul>

<a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

chapter19/blog/blogs/templates/blogs/edit_blog_post.html
{% extends 'blogs/base.html' %} {% block content %}

<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'blogs:edit_blog_post' blog_post.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">Save changes</button>
</form>

{% endblock content %}

chapter19/blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %} {% block content %}
<p>
  Blog helps you keep track of your learning, for any post you're interested in.
</p>
{% endblock content %}

chapter19/blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %} {% block content %}
<p>Add a new blog:</p>

<form action="{% url 'blogs:new_blog' %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">Add topic</button>
</form>

{% endblock content %}

chapter19/blog/blogs/templates/blogs/new_blog_post.html
{% extends "blogs/base.html" %} {% block content %}
<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

<p>Add a new blog_post:</p>

<form action="{% url 'blogs:new_blog_post' blog.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">Add blog_post</button>
</form>

{% endblock content %}